package com.m3utoolbox

import android.net.Uri

/**
 * M3U/M3U8 playlist parser.
 *
 * Important playback rule:
 * - The URL line is kept byte-for-byte (except surrounding whitespace/newline).
 * - Query parameters are parsed only for display/backward compatibility.
 * - Playback/export always uses Channel.originalUrl through getFullUrl().
 */
object M3UParser {

    fun parse(content: String): M3UFile {
        val m3uFile = M3UFile()
        val normalized = content.removePrefix("\uFEFF")
        val lines = normalized.lines()

        var currentCategory: Category? = null
        var pendingChannel: Channel? = null
        var currentUserAgent: String? = null
        var currentReferer: String? = null

        for (rawLine in lines) {
            val trimmed = rawLine.trim().removePrefix("\uFEFF")
            if (trimmed.isEmpty()) continue

            when {
                trimmed.startsWith("#EXTM3U", ignoreCase = true) -> {
                    parseExtM3U(trimmed, m3uFile)
                }

                trimmed.startsWith("#EXTVLCOPT:http-user-agent", ignoreCase = true) -> {
                    currentUserAgent = parseDirectiveValue(trimmed, "http-user-agent")
                }

                trimmed.startsWith("#EXTVLCOPT:http-referer", ignoreCase = true) -> {
                    currentReferer = parseDirectiveValue(trimmed, "http-referer")
                }

                trimmed.startsWith("#EXTINF", ignoreCase = true) -> {
                    val newChannel = parseExtInf(trimmed)
                    newChannel.userAgent = extractAttribute(trimmed, "http-user-agent")
                    newChannel.referer = extractAttribute(trimmed, "http-referer")
                    pendingChannel = newChannel
                }

                // The custom category marker generated by this application.
                trimmed.startsWith("# =") -> {
                    val categoryName = parseCategoryComment(trimmed)
                    if (categoryName.isNotEmpty()) {
                        currentCategory = Category(categoryName)
                        m3uFile.categories.add(currentCategory)
                    }
                }

                // Other M3U metadata/comments are not categories.
                trimmed.startsWith("#") -> Unit

                else -> {
                    val channel = pendingChannel ?: continue
                    parseUrlIntoChannel(trimmed, channel)

                    if (channel.userAgent.isNullOrBlank()) {
                        channel.userAgent = currentUserAgent
                    }
                    if (channel.referer.isNullOrBlank()) {
                        channel.referer = currentReferer
                    }

                    if (currentCategory == null) {
                        currentCategory = Category("未分类")
                        m3uFile.categories.add(currentCategory)
                    }
                    currentCategory.channels.add(channel)
                    pendingChannel = null
                }
            }
        }

        return m3uFile
    }

    /**
     * Parse the #EXTM3U header without requiring quoted values.
     * Handles UTF-8 BOM and values such as:
     *   #EXTM3U x-tvg-url="..."
     *   #EXTM3U url-tvg=https://...
     *   #EXTM3U catchup-days=7
     */
    private fun parseExtM3U(line: String, m3uFile: M3UFile) {
        val content = line.removePrefix("#EXTM3U").trim()
        if (content.isEmpty()) return

        parseKeyValueAttributes(content).forEach { (key, value) ->
            m3uFile.headerParams.add(HeaderParam(key, value))
        }
    }

    private fun parseExtInf(line: String): Channel {
        val channel = Channel()
        val afterPrefix = line.substringAfter("#EXTINF", "").trim()
        val lastComma = afterPrefix.lastIndexOf(',')

        if (lastComma == -1) {
            channel.displayName = "未命名"
            return channel
        }

        val attrsPart = afterPrefix.substring(0, lastComma)
        channel.displayName = afterPrefix.substring(lastComma + 1).trim().ifEmpty { "未命名" }
        channel.extinfAttributes.putAll(parseKeyValueAttributes(attrsPart))
        return channel
    }

    private fun parseCategoryComment(line: String): String {
        return line.removePrefix("#")
            .trim()
            .trim('=', ' ')
            .trim()
    }

    /**
     * Save the complete original URL and only then parse a compatibility view of it.
     * Never rebuild the playback URL from urlParams.
     */
    fun parseUrlIntoChannel(url: String, channel: Channel) {
        val rawUrl = url.trim()
        channel.originalUrl = rawUrl

        val uri = Uri.parse(rawUrl)
        channel.url = runCatching {
            uri.buildUpon().clearQuery().build().toString()
        }.getOrDefault(rawUrl)

        channel.urlParams.clear()
        val rawQuery = runCatching { uri.encodedQuery }.getOrNull()
        if (!rawQuery.isNullOrEmpty()) {
            rawQuery.split('&').forEach { param ->
                val idx = param.indexOf('=')
                if (idx > 0) {
                    channel.urlParams[param.substring(0, idx)] = param.substring(idx + 1)
                }
            }
        }
    }

    /** Parse #EXTVLCOPT:key=value, retaining quoted values when present. */
    private fun parseDirectiveValue(line: String, key: String): String? {
        val regex = Regex("""${Regex.escape(key)}\s*=\s*(.*)$""", RegexOption.IGNORE_CASE)
        return regex.find(line)?.groupValues?.get(1)
            ?.trim()
            ?.removeSurrounding("\"")
            ?.removeSurrounding("'")
            ?.ifEmpty { null }
    }

    private fun extractAttribute(line: String, key: String): String? {
        return parseKeyValueAttributes(line)[key]
    }

    /**
     * Attribute parser supporting quoted and unquoted M3U attributes.
     * Quoted values may contain spaces and commas.
     */
    private fun parseKeyValueAttributes(text: String): Map<String, String> {
        val result = linkedMapOf<String, String>()
        val regex = Regex("""([A-Za-z0-9_-]+)\s*=\s*("([^"]*)"|'([^']*)'|([^\s]+))""")
        regex.findAll(text).forEach { match ->
            val value = when {
                match.groupValues[3].isNotEmpty() -> match.groupValues[3]
                match.groupValues[4].isNotEmpty() -> match.groupValues[4]
                else -> match.groupValues[5]
            }
            result[match.groupValues[1]] = value
        }
        return result
    }

    fun generate(m3uFile: M3UFile): String {
        val sb = StringBuilder("#EXTM3U")
        m3uFile.headerParams.forEach { param ->
            sb.append(' ').append(param.key).append("=\"")
                .append(param.value.replace("\"", "&quot;"))
                .append('"')
        }
        sb.append('\n')

        for (category in m3uFile.categories) {
            sb.append("# ============ ").append(category.name).append(" ============\n")
            for (channel in category.channels) {
                if (!channel.userAgent.isNullOrBlank()) {
                    sb.append("#EXTVLCOPT:http-user-agent=")
                        .append(channel.userAgent).append('\n')
                }
                if (!channel.referer.isNullOrBlank()) {
                    sb.append("#EXTVLCOPT:http-referer=")
                        .append(channel.referer).append('\n')
                }

                val attrs = StringBuilder()
                val groupTitle = channel.extinfAttributes["group-title"] ?: category.name
                channel.extinfAttributes.forEach { (key, value) ->
                    if (key != "group-title" && key != "http-user-agent" && key != "http-referer") {
                        attrs.append(' ').append(key).append("=\"").append(value).append('"')
                    }
                }

                sb.append("#EXTINF:-1")
                    .append(attrs)
                    .append(" group-title=\"")
                    .append(groupTitle)
                    .append("\",")
                    .append(channel.displayName)
                    .append('\n')
                    .append(channel.getFullUrl())
                    .append('\n')
            }
        }
        return sb.toString()
    }
}
